export const roleHierarchy: { [key: string]: number } = {
  user: 0,
  staff: 1,
  admin: 2,
};

// Role-Permission Matrix
export const ROLE_PERMISSIONS = {
  user: [
    'profile.read',
    'profile.update',
    'transactions.read.own',
    'incidents.read',
  ],
  staff: [
    'reports.create',
    'reports.read.all',
    'reports.update.all',
    'transactions.read.all',
    'transactions.create',
    'transactions.update',
    'incidents.create',
    'incidents.read.all',
    'incidents.update.own',
    'profile.read',
    'profile.update',
    'topup-requests.read.all',
    'settlements.read.all',
    'create_notification',
    'manage_notification_templates',
    'view_notification_analytics',
  ],
  admin: [
    'reports.create',
    'reports.read.all',
    'reports.update.all',
    'reports.delete.all',
    'reports.verify',
    'transactions.read.all',
    'transactions.create',
    'transactions.update',
    'transactions.delete',
    'incidents.create',
    'incidents.read.all',
    'incidents.update.all',
    'incidents.delete.all',
    'users.create',
    'users.read.all',
    'users.update.all',
    'users.delete.all',
    'roles.assign',
    'profile.read',
    'profile.update',
    'system.settings',
    'topup-requests.read.all',
    'topup-requests.update',
    'settlements.read.all',
    'settlements.create',
    'operators.read.all',
    'operators.create',
    'operators.update',
    'suppliers.read.all',
    'suppliers.create',
    'suppliers.update',
    'products.read.all',
    'products.create',
    'products.update',
    'create_notification',
    'manage_notification_templates',
    'view_notification_analytics',
    'offer:create',
    'offer:read',
    'offer:update',
    'offer:delete',
  ],
};

// Permission descriptions for documentation
export const PERMISSION_DESCRIPTIONS = {
  'reports.create': 'Create new election reports',
  'reports.read.own': 'View own election reports',
  'reports.read.all': 'View all election reports',
  'reports.read.public': 'View public election reports',
  'reports.update.own': 'Update own election reports',
  'reports.update.all': 'Update all election reports',
  'reports.delete.own': 'Delete own election reports',
  'reports.delete.all': 'Delete all election reports',
  'reports.verify': 'Verify election reports',
  'incidents.create': 'Create new incidents',
  'incidents.read.all': 'View all incidents',
  'incidents.read.public': 'View public incidents',
  'incidents.update.own': 'Update own incidents',
  'incidents.update.all': 'Update all incidents',
  'incidents.delete.all': 'Delete all incidents',
  'users.create': 'Create new users',
  'users.read.all': 'View all users',
  'users.update.all': 'Update all users',
  'users.delete.all': 'Delete all users',
  'roles.assign': 'Assign roles to users',
  'profile.read': 'View own profile',
  'profile.update': 'Update own profile',
  'system.settings': 'Manage system settings',
  'topup-requests.read.all': 'View all topup requests',
  'topup-requests.update': 'Update topup requests',
  'settlements.read.all': 'View all settlements',
  'settlements.create': 'Create new settlements',
  'operators.read.all': 'View all operators',
  'operators.create': 'Create new operators',
  'operators.update': 'Update operators',
  'suppliers.read.all': 'View all suppliers',
  'suppliers.create': 'Create new suppliers',
  'suppliers.update': 'Update suppliers',
  'products.read.all': 'View all products',
  'products.create': 'Create new products',
  'products.update': 'Update products',
  create_notification: 'Create and send notifications to users',
  manage_notification_templates: 'Manage notification templates',
  view_notification_analytics: 'View notification analytics',
  'offer:create': 'Create new offers',
  'offer:read': 'Read offers',
  'offer:update': 'Update offers',
  'offer:delete': 'Delete offers',
};
